config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  get   'register'      => 'users#new',         as: 'new_register'
  get   'users/new'     => 'users#new'
  post  'register'      => 'users#create',      as: 'register'
  post  'users'         => 'users#create'
  get   'users/:id'     => 'users#show',        as: 'user'
  get   'login'         => 'sessions#new',      as: 'new_login'
  get   'sessions/new'  => 'sessions#new'
  post  'login'         => 'sessions#create',   as: 'login'
  post  'sessions'      => 'sessions#create'
  delete    'logout'    => 'sessions#destroy',  as: 'logout'
  delete    'sessions'  => 'sessions#destroy'

  get   'events'        => 'events#index',      as: 'events'
  post  'events'        => 'events#create',     as: 'create_event'
  get   'events/:id'    => 'events#show',       as: 'event'
  delete 'events/:id'   => 'events#destroy',    as: 'delete_event'

  post  'join_event'    => 'attends#create',    as: 'join_event'
  delete 'leave_event'  => 'attends#destroy',   as: 'leave_event'

  post  'messages'      => 'messages#create',   as: 'create_message'

end

app/models/attend.rb
class Attend < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :attends
  has_many :messages
  has_many :attendees, through: :attends, source: :user

  validates :name, :city, presence: true, length: { in: 2..30 }

  validates :state, presence: true, length: { is: 2 }

  def future_date
      if date.present? && date < Date.now
          errors.add(:date, "can't be in the past.")
      end
  end





end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :content, presence: true, length: { minimum: 2 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :events
  has_many :attends
  has_many :messages
  has_many :attending, through: :attends, source: :event

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  before_save :downcase

  validates :first_name, :last_name,  presence: true

  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }

  validates :city, presence: true, length: { in: 2..30 }

  validates :state, presence: true, length: { is: 2 }

  def downcase
      self.first_name.downcase!
      self.last_name.downcase!
      self.email.downcase!
      self.city.downcase!
      self.state.downcase!
  end






end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	  User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController

    def create
        Attend.create(attend_params)

        return redirect_to :back
    end

    def destroy

    end

    private
        def attend_params
            params.require(:attend).permit(:event_id).merge(user: current_user)
        end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def index
        @events = Event.where(state: current_user.state)

        @out_of_state = Event.where.not(state: current_user.state)
    end

    def create
        @event = Event.create(event_params)

        if @event.valid?
            Attend.create(user: current_user, event: @event)

            return redirect_to events_path
        end

        flash[:errors] = @event.errors.full_messages

        return redirect_to events_path
    end

    def show
        @event = Event.find(params[:id])
    end

    def destroy
        @event = Event.find(params[:id])

        @event.destroy

        return redirect_to events_path
    end

    private
        def event_params
            params.require(:event).permit(:name, :date, :city, :state).merge(user: current_user)
        end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
        event_id = params[:message][:event_id]
        @message = Message.create(message_params)

        return redirect_to event_path(event_id) if @message.valid?

        flash[:errors] = @message.errors.full_messages

        return redirect_to event_path(event_id)
    end

    private
        def message_params
            params.require(:message).permit(:content, :event_id).merge(user: current_user)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by_email(params[:user][:email])

        if user
            if user.try(:authenticate, params[:user][:password])
                session[:user_id] = user.id

                return redirect_to events_path
            end

            flash[:errors] = ['Password is not correct.']
        else
            flash[:errors] = ['Account not found, please register first.']
        end

        return redirect_to new_login_path
    end

    def destroy
        session.delete(:user_id) if session[:user_id]

        return redirect_to new_login_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end

    def create
        user = User.create(user_params)

        if user.valid?
            session[:user_id] = user.id

            return redirect_to events_path
        end

        flash[:errors] = user.errors.full_messages

        return redirect_to :back
    end

    def show
        @user = User.find(params[:id])
    end

    private
        def user_params
            params.require(:user).permit(:first_name, :last_name, :email, :city, :state, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h5>Welcome, <%= current_user.first_name.capitalize %>!</h5>

<!-- Events in our state -->
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Location</th>
            <th>Host</th>
            <th>Action/Status</th>
        </tr>
    </thead>
    <tbody>
        <% @events.each do |event| %>
            <tr>
                <td><a href="<%= event_path event.id %>"><%= event.name %></a></td>
                <td><%= event.date %></td>
                <td><%= event.city %></td>
                <td><%= event.user.first_name %></td>
                <td>
                    <% if event.user == current_user %>
                        <form action="<%= delete_event_path event.id %>" method="post">
                            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                            <input type="hidden" name="_method" value="delete" />

                            <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                        </form>
                    <% else %>
                        <% if event.attendees.include? current_user %>
                        Joined
                            <form action="<%= leave_event_path %>" method="post">
                                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                                <input type="hidden" name="attend[event_id]" value="<%= event.id %>" />

                                <button class="btn btn-sm btn-warning" type="submit">Cancel</button>
                            </form>
                        <% else %>
                            <!-- Join -->
                            <form action="<%= join_event_path %>" method="post">
                                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                                <input type="hidden" name="attend[event_id]" value="<%= event.id %>" />

                                <button class="btn btn-sm btn-primary" type="submit">Join</button>
                            </form>
                        <% end %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<!-- Events out of state -->
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Location</th>
            <th>State</th>
            <th>Host</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @out_of_state.each do |event| %>
            <tr>
                <td><a href="<%= event_path event.id %>"><%= event.name %></a></td>
                <td><%= event.date %></td>
                <td><%= event.city %></td>
                <td><%= event.state %></td>
                <td><%= event.user.first_name %></td>
                <td>
                    <% if event.user == current_user %>
                        <form action="<%= delete_event_path event.id %>" method="post">
                            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                            <input type="hidden" name="_method" value="delete" />

                            <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                        </form>
                    <% else %>
                        <% if event.attendees.include? current_user %>
                        Joined
                            <form action="<%= leave_event_path %>" method="post">
                                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                                <input type="hidden" name="attend[event_id]" value="<%= event.id %>" />

                                <button class="btn btn-sm btn-warning" type="submit">Cancel</button>
                            </form>
                        <% else %>
                            <!-- Join -->
                            <form action="<%= join_event_path %>" method="post">
                                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                                <input type="hidden" name="attend[event_id]" value="<%= event.id %>" />

                                <button class="btn btn-sm btn-primary" type="submit">Join</button>
                            </form>
                        <% end %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<div class="row">
    <div class="col-sm-12">
        <h4>Add Event</h4>
    </div>
</div>

<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <form action="<%= create_event_path %>" method="post" class="form">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
            <!-- Name -->
            <div class="form-group">
                <input type="text" name="event[name]" class="form-control" id="name" placeholder="Name" />
            </div>
            <!-- Date -->
            <div class="form-group">
                <input type="date" name="event[date]" class="form-control" id="date" placeholder="Date" />
            </div>
            <!-- Location -->
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-8">
                        <input type="text" name="event[city]" class="form-control" id="city" placeholder="City" />
                    </div>
                    <div class="col-sm-4">
                        <input type="text" name="event[state]" class="form-control" id="state" placeholder="State" />
                    </div>
                </div>
            </div>
            <!-- Submit -->
            <div class="form-group">
                <button class="btn btn-success" type="submit">Add Event</button>
            </div>
        </form>
    </div>
    <div class="col-sm-2"></div>
</div>

app/views/events/show.html.erb
<div class="row">
    <div class="col-sm-6">
        <h5><%= @event.name %></h5>

        <p>Host: <%= @event.user.first_name %></p>
        <p>Date: <%= @event.date %></p>
        <p>Location: <%= @event.city %>, <%= @event.state.upcase %></p>

        <p>People who are joining the event: <%= @event.attendees.count %></p>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Location</th>
                    <th>State</th>
                </tr>
            </thead>
            <tbody>
                <% @event.attendees.each do |user| %>
                    <% unless user == @event.user %>
                        <tr>
                            <td><%= user.first_name %> <%= user.last_name %></td>
                            <td><%= user.city %></td>
                            <td><%= user.state.upcase %></td>
                        </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h4>Discussion about this event:</h4>
        <div id="messages">
            <% if @event.messages %>
                <% @event.messages.each do |message| %>
                    <p><%= message.user.first_name %> says: <%= message.content %></p>
                    <p>------------------</p>
                <% end %>
            <% else %>
                <p>Empty</p>
            <% end %>
        </div>

        <form action="<%= create_message_path %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
            <input type="hidden" name="message[event_id]" value="<%= @event.id %>" />

            <textarea name="message[content]"></textarea>

            <button type="submit">Submit Comments</button>
        </form>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Belt Reviewer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%= root_path %>">Belt Reviewer</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if current_user %>
              <li class="nav-item active">
                <a class="nav-link" href="<%= logout_path %>" data-method="delete">Logout</a>
              </li>
          <% else %>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_register_path %>">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_login_path %>">Login</a>
              </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
        <!-- Errors -->
        <% if flash[:errors] %>
            <% flash[:errors].each do |error| %>
                <p class="text-danger"><%= error %></p>
            <% end %>
        <% end %>

        <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="row">
    <div class="col-sm-12">
        <h4>Register</h4>
    </div>
</div>

<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <form action="<%= register_path %>" method="post" class="form">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
            <!-- First Name -->
            <div class="form-group">
                <input type="text" name="user[first_name]" class="form-control" id="first_name" placeholder="First name" />
            </div>
            <!-- Last Name -->
            <div class="form-group">
                <input type="text" name="user[last_name]" class="form-control" id="last_name" placeholder="Last name" />
            </div>
            <!-- Email -->
            <div class="form-group">
                <input type="email" name="user[email]" class="form-control" id="email" placeholder="Email" />
            </div>
            <!-- Location -->
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-8">
                        <input type="text" name="user[city]" class="form-control" id="city" placeholder="City" />
                    </div>
                    <div class="col-sm-4">
                        <input type="text" name="user[state]" class="form-control" id="state" placeholder="State" />
                    </div>
                </div>
            </div>
            <!-- Password -->
            <div class="form-group">
                <input type="password" name="user[password]" class="form-control" id="password" placeholder="Password" />
            </div>
            <!-- Password Confirmation -->
            <div class="form-group">
                <input type="password" name="user[password_confirmation]" class="form-control" id="password_confirmation" placeholder="Password Confirmation" />
            </div>
            <!-- Submit -->
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Register</button>
            </div>
        </form>
    </div>
    <div class="col-sm-2"></div>
</div>

app/views/users/show.html.erb
<h4>Show Page</h4>

<p>First Name: <%= @user.first_name %></p>